services:
  - type: web
    name: draft-ai-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false  # You'll need to set this in Render dashboard 